
const Food1=[
    {id:1,
        url:'http://localhost:3000/image/Indfood-1.jpg',
        rate:'50',
        title:'Idly',
        quantity:'2 pieces',
        star:4.5,
        description:'Idli are a type of savoury rice cake, originating from the Indian subcontinent, popular as breakfast foods in Southern India and in Sri Lanka. The cakes are made by steaming a batter consisting of fermented white gram whole and rice rava. and dipped into sambar. its also called as dip sambar idli.',title:'IndianFood'},
    {id:2,
        url:'http://localhost:3000/image/Indfood-2.jpg',
        rate:'100',
        title:'Dosa',
        quantity:'2 pieces',
        star:4.5,
        description:'A thin and crispy pancake prepared with fermented dosa batter which is topped with red garlic chutney and potato masala. the appearance and texture is very similar to world famous masala dosa. but the main difference lies with the red garlic chutney spread topped on bangalore dosa.',
        fakerate:900},
    {id:3,
        url:'http://localhost:3000/image/Indfood-3.jpg',
        rate:'100',
        title:'Puri',
        quantity:'2 pieces',
        star:4.5,
        description:'South Indian style potato masala made with boiled, crumbled potatoes in mild, flavorful gravy. It is served with hot Poori which is a deep-fried bread made from unleavened whole-wheat flour'},
    {id:4,
        url:'http://localhost:3000/image/Indfood-4.jpg',
        rate:'100',
        title:'Upma',
        quantity:'1 Serve',
        star:3,
        description:"The best aromatic upma topped with vegetables and ghee and it comes with more vegetables. Staying consious of one's health is the way to go, thus is a light upma made of wheat grains and vegetable "},
    {id:5,
        url:'http://localhost:3000/image/Indfood-5.jpg',
        rate:'100',
        title:'Chappathi',
        quantity:'2 pieces',
        star:5,
        description:'Traditional whole wheat Tawa special,What are the few lines for chapati Chapati is Indian flat bread made of wheat flour. It is the staple food in the North Asian countries especially in North India and Pakistan. It can also be made of various other flours like the jowar, bajra, soya, raji etc.'},
    {id:6,
        url:'http://localhost:3000/image/Indfood-6.jpg',
        rate:'100',
        title:'Biriyani',
        quantity:'1 Serve',
        star:4,
        description:'Rich in taste and creamy in texture. Think we are talking about a dessert? Well,this biryani might as well be one with the way it melts in your mouth. Tender chicken is marinated in yogurt&spices to make this biryani delicious'},
    {id:7,
        url:'http://localhost:3000/image/Indfood-7.jpg',
        rate:'100',
        title:'Fish fry',
        quantity:'2 pieces',
        star:5,
        description:'Fish fry is cooked by coating it with flours and spices which adds crispness and spiciness.fish battered and fried with authentic andra spices. And served in a traditional south Indian masala - Served with Res Chutni & Onion Salad'},
    {id:8,
        url:'http://localhost:3000/image/Indfood-8.jpg',
        rate:'100',
        title:'Crab',
        quantity:'2 pieces',
        star:4.5,
        description:'Singapore style chili pepper fried soft shell crab served with jasmine rice. Hand picked crab prepared with traditional spices'},
    {id:9,
        url:'http://localhost:3000/image/Indfood-9.jpg',
        rate:'100',
        title:'Prawn',
        quantity:'6 pieces',
        star:5,
        description:'King prawns stir fried in a  hunan style soy-chilli sause with fresh chillies,lemongrass,kaffir lime leaves,shallots,onion and celery'},
]
const food2=[
        {id:2.1,
            url:'http://localhost:3000/image/italifood-1.jpg',
            rate:'300',
            title:'Spaghetti',
            quantity:'2 pieces',
            star:4.5},
        {id:2.2,
            url:'http://localhost:3000/image/italifood-2.jpg',
            rate:'250',
            title:'Lasagna',
            quantity:'1 Serve',
            star:4.5},
        {id:2.3,
            url:'http://localhost:3000/image/italifood-3.jpg',
            rate:'500',
            title:' Risotto milanese',
            quantity:'1 serve',
            star:5},
        {id:2.4,
                url:'http://localhost:3000/image/italifood-4.jpg',
                rate:'700',
                title:'Ratatouille',
                quantity:'2 serve',
                star:4.5},
        {id:2.5,
                 url:'http://localhost:3000/image/italifood-5.jpg',
                rate:'200',
                title:'Tiramisu',
                quantity:'1 serve',
                star:4.5},
        {id:2.6,
                url:'http://localhost:3000/image/italifood-6.jpg',
                rate:'439',
                title:'Frittata',
                quantity:'2 serve',
                star:4.5},]
            
                
export default Food1